### ISSUE TITLE
Authrep does not seem to report

### ISSUE THREAD

**Issue by picsoung** [3scale/3scale_ws_api_for_nodejs#20]
I have installed the plugin in my project trying to use `authrep` to authorize and report.

Authorize part works great, but the reporting is not shown in my analytics dashboard.

```javascript

client.authrep({ app_id: "APP_ID",
                 app_key: "APP_KEY" }, function(response){
          if(response.is_success()) {
               console.log("works")
          } else {
              throw new Error("not authorized " + response.error_message);
          }
        });

```

**Comment by vdel26** [comment]
@picsoung you need to pass the usage as a parameter in the following way:
```js
client.authrep({ app_id: "APP_ID",
                 app_key: "APP_KEY" 
                 usage: { hits: 1 }}, function(response){
          if(response.is_success()) {
               console.log("works")
          } else {
              throw new Error("not authorized " + response.error_message);
          }
        });
```

We should probably add a default usage of "hits: 1" when the usage object is not included in the parameters, especially considering that the other libraries are already doing it:
(https://github.com/3scale/3scale_ws_api_for_python/blob/master/ThreeScalePY.py#L173)
