### ISSUE TITLE
Tests suite crendentials

### ISSUE THREAD

**Issue by simonrenoult** [3scale/3scale_ws_api_for_nodejs#24]
Hi,

Should we run the project tests (`npm test`) against our own 3scale application or is there an available application to do so ? I saw that there's one used in Jenkins, can we use it (given you provide the `provider_key`) ? 

Thanks !

**Comment by vdel26** [comment]
The credentials defined in the `.travis.yml` file are what we use for internal testing, that is why the provider_key is private. But you are free to run the tests using your own 3scale credentials: you just need to set the following environment variables:
- `TEST_3SCALE_APP_ID`
- `TEST_3SCALE_APP_KEY`
- `TEST_3SCALE_PROVIDER_KEY`

The first two should correspond to one of the applications in your 3scale account and the provider key the key that identifies you as a 3scale customer (can be found in the "Account" menu on the top right corner of your admin portal).

**Comment by simonrenoult** [comment]
Thanks, I was not careful enough when I read the `README.md` and missed this part : `Please note that you will first need to set the following environment variables using your own 3scale keys`
